### PR TITLE
revert calling current_data in process_stores, since it can blow up if t...

### PR DESCRIPTION
**Pull request by grosser**
...here is no store found

@osheroff @marcosvm @dragonfax 

### Risks
 - whoever calls process_stores directly might be in for a surprise ...

### CODE REVIEW

**Comment by marcosvm** [comment]
phew. +1

**Comment by grosser** [comment]
do you remember why you added this ? is anyone using it ?

**Comment by marcosvm** [comment]
I was trying to refactor a huge blob of code in order to separate the
saving to the database from the uploading to S3, as a transaction is kept
open while the file is being uploaded. This cause a whole lot of lock
timeouts on airbrake.

**Comment by grosser** [comment]
ok, I'll remove it for now and if we want to revisit it we can try to get it in without blowing up :)

**Comment by marcosvm** [comment]
Great. Thanks.

**Pull request merged**
