### PR TITLE
Compatibility with Rails 5.0

### PR DESCRIPTION
**Pull request by pschambacher**
/cc @grosser @osheroff @bquorning

### CODE REVIEW

**Comment by bquorning** [comment]
:+1:

**Comment by grosser** [comment]
:+1: :heart: great drive-by cleanup too :)

**Comment by pschambacher** [comment]
Don't have permissions on rubygems to release...

**Comment by osheroff** [comment]
I don't think we release this thing on rubygems.  probably just privately.

**Comment by grosser** [comment]
https://rubygems.org/gems/attachment_zen 
1.1.0 is out now

**Comment by grosser** [comment]
give me your rubygems emails if you want to get added :)

**Comment by pschambacher** [comment]
@grosser it's my zendesk email. Do we have any list of gems so I can be added everywhere?

**Comment by grosser** [comment]
Don't think we have a list of all our gems ... not adding you now since I'll move it to private soonish ...

**Comment by pschambacher** [comment]
we should move some gems in the zendesk domain as well, would make it simpler for everybody

**Comment by grosser** [comment]
As long as we keep the zendesk prefix it should work out nicely

**Pull request merged**
